### ISSUE TITLE
Logout functionality

### ISSUE THREAD

**Issue by DamyanBG** [DamyanBG/cat-of-the-day-front-end#1]
On click on Logout button from the header menu, implement logic to make request to /uploader/logout or /voter/logout , depending on that is user logged in as participant or voter.

**Comment by DamyanBG** [comment]
Yes, I can assign the task to you. Give me 5 minutes to commit the last changes which I am making. Please, add your work via Pull Request

**Comment by H4K3R13** [comment]
Ok. I can give it a try . Thank for the opportunity

**Comment by DamyanBG** [comment]
You welcome. If you have questions - ping me!

BTW you can take a look at urls.ts in the common folder and change the HOST_URL to AZURE_HOST_URL. I just deployed the back end on the Azure Cloud and you can easily use the back end.

**Comment by DamyanBG** [comment]
I made it.
