### ISSUE TITLE
Investigate the UI for smart phone

### ISSUE THREAD

**Issue by DamyanBG** [DamyanBG/cat-of-the-day-front-end#2]
This app have to be in good shape on smart phone screen size. Investigate the UI and raise bugs if there are any!

**Comment by Pragyan14** [comment]
I want to work on this issue please assign me this issue.

**Comment by Pragyan14** [comment]
The elements of the hamburger dropdown menu are not all centered.

**Comment by DamyanBG** [comment]
Thank you
